### NumPy Module

In [2]:
import numpy as np

In [4]:
a1 = np.array([1,2,3,4,5])
print(a1)

[1 2 3 4 5]


In [6]:
a2 = np.array([1,2,3,4,5],float)
print(a2)

[1. 2. 3. 4. 5.]


In [7]:
a1 = np.append(a1,45)
print(a1)

[ 1  2  3  4  5 45]


In [8]:
a1 = np.delete(a1,5)
print(a1)

[1 2 3 4 5]


In [10]:
print (type(a1))

<class 'numpy.ndarray'>


In [11]:
print (a1.dtype)

int32


In [12]:
print(a1.ndim)

1


In [13]:
print(a1.size)

5


In [14]:
print(a1.shape)

(5,)


In [15]:
a5 = np.array([[2,3,5],[6,2,3]])
print("Value of a5: ",a5)
print("Type of a5: ",type(a5))
print("DataType of a5: ",a5.dtype)
print("Dimensions of a5: ",a5.ndim)
print("Size of a5: ", a5.size)
print("Shape of a5: ",a5.shape)

Value of a5:  [[2 3 5]
 [6 2 3]]
Type of a5:  <class 'numpy.ndarray'>
DataType of a5:  int32
Dimensions of a5:  2
Size of a5:  6
Shape of a5:  (2, 3)


In [16]:
a6 = np.linspace(5,20,10)
print(a6)

[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]


In [18]:
a = np.array([1,2,3,10,15,49])  
print("The array:",a)  
print("The maximum element:",a.max())  
print("The minimum element:",a.min())  
print("The sum of the elements:",a.sum())  

The array: [ 1  2  3 10 15 49]
The maximum element: 49
The minimum element: 1
The sum of the elements: 80


In [19]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 3.16227766 3.87298335 7.        ]


In [20]:
print(np.std(a))

16.69996673316713


In [21]:
print(np.mean(a))

13.333333333333334


In [23]:
a = np.array([1,2,3,10,15,4])
b = np.array([6,4,2,12,20,40])  
print(a)
print(b)
print(a+b)

[ 1  2  3 10 15  4]
[ 6  4  2 12 20 40]
[ 7  6  5 22 35 44]


In [26]:
print(a-b)

[ -5  -2   1  -2  -5 -36]


In [27]:
print(a*b)

[  6   8   6 120 300 160]


In [28]:
print(a/b)

[0.16666667 0.5        1.5        0.83333333 0.75       0.1       ]
